### ISSUE TITLE
Inky Impression Image

### ISSUE THREAD

**Issue by gibbiemonster** [Hothomir/weather-report#15]
Image of the inky Impression running.

Colors need to be reversed, but that's on me.![PXL_20220324_015105533~2.jpg](https://user-images.githubusercontent.com/49456798/159826207-8dcf940d-a294-41c7-8f60-8566b6e01ea1.jpg)

If you only need icons this should work fine

**Comment by gibbiemonster** [comment]
(cc: @Hothomir)

**Comment by Hothomir** [comment]
That came out much better than I expected, great!

**Comment by gibbiemonster** [comment]
Awesome! I'm trying to experiment with the correct colors so it *looks* good as well. I'll keep you posted!

**Comment by gibbiemonster** [comment]
Please see #17 for further discussion.
